[package]
name = "yew-frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = { version = "1.3.0" }
yew = { version = "0.21", features = ["csr"] }
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
