name: GitHub Pages

on:
  push:
    branches:
      - "**"
    tags:
      - "*"

jobs:
  build_and_deploy:
    name: Rust project for all branches
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: jetli/trunk-action@v0.5.0
        with:
          version: "latest"

      - run: rustup target add wasm32-unknown-unknown

      - name: Set build and public directory for branches
        run: |
          if [ "${GITHUB_REF##*/}" = "main" ]; then
            echo "BUILD_DIR=./dist" >> $GITHUB_ENV
            echo "PUBLIC_URL=/berliners-halreslib/" >> $GITHUB_ENV
          else
            echo "BUILD_DIR=./dist" >> $GITHUB_ENV
            echo "PUBLIC_URL=/berliners-halreslib/" >> $GITHUB_ENV
          fi

      - run: mkdir -p $BUILD_DIR
      - run: echo $BUILD_DIR $PUBLIC_URL
      - run: cd yew-frontend && trunk build --release --dist $BUILD_DIR --public-url $PUBLIC_URL

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./yew-frontend/dist
          keep_files: true
